### ISSUE TITLE
No module named yatools

### ISSUE THREAD

**Issue by fridtjof** [DGA-MI-SSI/YaCo#27]
This is what I get when running YaCo in IDA (after applying #26 to fix path names)

```
YaCo: error during run
Traceback (most recent call last):
  File "/Applications/IDA Pro 7.0/ida.app/Contents/MacOS/plugins/yaco_plugin.py", line 88, in run
    import YaCo
  File "/Applications/IDA Pro 7.0/ida.app/Contents/MacOS/plugins/YaTools/YaCo/YaCo.py", line 35, in <module>
    import hooks
  File "/Applications/IDA Pro 7.0/ida.app/Contents/MacOS/plugins/YaTools/YaCo/hooks.py", line 23, in <module>
    import yatools
ImportError: No module named yatools
```

Obviously, there is no file called yatools in neither the YaCo nor the bin dir

**Comment by bamiaux** [comment]
A bug from the repo patch merge, please try https://github.com/DGA-MI-SSI/YaCo/tree/repo_fixes

**Comment by fridtjof** [comment]
That worked, thanks!
