### ISSUE TITLE
ssh-agent integration

### ISSUE THREAD

**Issue by tpo-anssi** [DGA-MI-SSI/YaCo#8]
The plugin seems to not manage agents to manage ssh-keys authentication with git repos.

```
INFO:YaCo:YaCo.save()
Traceback (most recent call last):
  File "plugins/YaTools/YaCo/ImportExport/YaToolRepoManager.py", line 459, in update_cache
    self.fetch_origin()
  File "plugins/YaTools/YaCo/ImportExport/YaToolRepoManager.py", line 388, in fetch_origin
    self.repo.fetch()
  File "plugins/YaTools/bin/YaToolsPy32.py", line 1956, in fetch
    return _YaToolsPy32.GitRepo_fetch(self, *args)
RuntimeError: Failed to authenticate SSH session: Unable to open public key file
```

**Comment by bamiaux** [comment]
ssh-agent support is probably not compiled properly in libssh2, probably just a missing define

**Comment by bamiaux** [comment]
Fixed in upcoming release
